### ISSUE TITLE
debug: goerli nonce

### ISSUE THREAD

**Issue by anna-carroll** [nomad-xyz/monorepo#120]
when i log the deploy transaction, the nonce is:
`  "nonce": 323,`

but on the block explorer when i pull up the [txs from the deployer account](https://goerli.etherscan.io/txs?a=0xa4849f1D96B26066f9C631FCdc8F1457D27Fb5EC) it shows the [last tx from this account](https://goerli.etherscan.io/tx/0x8517d07baef791509a037c17adb62c34e11bed7a311e9d87af798ac4d301d896) had nonce `310`…

deploy script is hanging indefinitely, need to figure it out...

**Comment by prestwich** [comment]
cc @yourbuddyconner 

This is why we dropped goerli support in the first place. the mempool is an absolute piece of junk. 323 is the "correct" nonce because there are 13 unconfirmed transactions hanging out in the alchemy mempool that for whatever reason are never being mined. the RPC returns the (subjectively correct) next nonce. but because 311 is out there 🌈 ✨somewhere in the void 🌈 ✨ never confirming, 323 can never confirm.

It is hard to see how to resolve this issue, as it's a problem with the block producers never including txns that are circulating on the network and/or with alchemy/infura holding txns in their mempool long after they ought to drop them.

Some solutions:
- Poll etherscan instead of alchemy for the "next" nonce according to them 🙄 
- use a nonce manager and populate it with the earlier nonce using something like [provider.getTransactionCount(deployerAddress, -10)](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/base-provider.ts#L1443)
- any chance we have partners that run goerli PoA nodes that we could leverage to help us get txns in reliably?

**Comment by yourbuddyconner** [comment]
@ltchang2019 is going to investigate using other RPC providers that might have different behavior here, will investigate the "friends running a Goerli node" angle as well.

**Comment by ltchang2019** [comment]
Update here, deploying to Goerli using Infura endpoint worked. We also make sure to wait 5 confirmations for each transaction (or async promise of transactions) before submitting a set of new transactions. This approximately 75 seconds.

**Comment by anna-carroll** [comment]
from @ltchang2019 

> Update on Goerli:
> Was able to deploy goerli in the dev setup with rinkeby, kovan, and xdai :tada: infura endpoint + more confirmations got it to work
> Changes + output are on the branch [luke/goerli](https://github.com/nomad-xyz/monorepo/tree/luke/goerli)
> Governance transactions to enroll goerli to existing setups is in output folder on branch but not yet executed cc [@anna](https://nomad-xyz.slack.com/team/U02R8S3RANM)
> Will push PR to rust to update development.json config
